Add 1

diff --git a/web_server/1-install_nginx_web_server b/web_server/1-install_nginx_web_server
--- a/web_server/1-install_nginx_web_server
+++ b/web_server/1-install_nginx_web_server
@@ -12,7 +12,7 @@ if ! [ -x "$(command -v nginx)" ]; then
 fi
 
 # Create a basic HTML file with required content
-echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
+echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
 
 # Check if index.html was created
 if ! [ -f /var/www/html/index.html ]; then
@@ -21,7 +21,15 @@ if ! [ -f /var/www/html/index.html ]; then
 fi
 
 # Restart Nginx without using systemctl
-sudo /etc/init.d/nginx restart
+sudo service nginx restart
+
+# Check if Nginx restarted successfully
+nginx_status=$(sudo service nginx status)
+if ! echo "$nginx_status" | grep -q "active (running)"; then
+  echo 'Error: Nginx failed to restart.' >&2
+  exit 1
+fi
 
 exit 0
+
 
